# Generated by Django 5.2.5 on 2025-08-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantel',
            name='precio',
        ),
    ]
